### ISSUE TITLE
[Suggestion] Skin Property API

### ISSUE THREAD

**Issue by MaRoTheTroLLeR** [Yive/MCAPI-Support#10]
Hello,

I wanted to ask if you could add API that returns Skin Property just like Mojang, so i can use it in SkinsRestorer without that Rate Limited issue by Mojang ?

Thanks :)

**Comment by Yive** [comment]
What do you mean by "Skin Property"?

**Comment by MaRoTheTroLLeR** [comment]
Like this  https://sessionserver.mojang.com/session/minecraft/profile/<uuid>

See the UUID -> Profile + Skin/Cape here http://wiki.vg/Mojang_API

Is it possible ?

**Comment by Yive** [comment]
Oh that, yeah I suppose I could add that, but it may take up to a week since I need to buy some more proxies for that. Do you have a rough estimate on how many servers use your plugin? Just so that I can roughly figure out the amount of proxies I'll need.

**Comment by MaRoTheTroLLeR** [comment]
The plugin has around 35 000 downloads. I dont know how many servers are using it now.
How much a proxy costs ?

**Comment by Yive** [comment]
Okay then, I'll just go off of the amount of downloads from the current version. well it depends on which host I choose, since the host I used to use for proxies stopped selling the packages I used for proxies.

**Comment by MaRoTheTroLLeR** [comment]
I wanted to donate 2.50 but im not permitted :D lel xD

**Comment by MaRoTheTroLLeR** [comment]
Still waiting for this dude :)

**Comment by Yive** [comment]
Sorry took so long, didn't get to set the proxies up till a while ago & forgot to reply back to this. You most likely already have noticed that the properties have already been added to the UUID api though.

**Comment by MaRoTheTroLLeR** [comment]
Yes, but they have missing "signature"

2015-11-07 11:25 GMT+02:00 Yive <notifications@github.com>:

**Comment by Yive** [comment]
oops didn't know that was a thing, just added it.

**Comment by MaRoTheTroLLeR** [comment]
What is the response code if mcapi fails to get the skin from mojang ? 429 ?

2015-11-08 0:49 GMT+02:00 Yive <notifications@github.com>:

**Comment by MaRoTheTroLLeR** [comment]
Also, Can you make the properties to be returned like this ?

    "properties": [
        {
            "name": "textures",
            "value": "<base64 string>",
            "signature": "<base64 string; signed data using
Yggdrasil's private key>" // Only provided if ?unsigned=false is
appended to url
        }
    ]


They are returned like this by mcapi.ca

    "properties": {
            "name": "textures",
            "value": "<base64 string>",
            "signature": "<base64 string; signed data using
Yggdrasil's private key>" // Only provided if ?unsigned=false is
appended to url
        }
    Name, value and signature must be in array. :)

2015-11-08 2:02 GMT+02:00 Th3Tr0LLeR . <marooohd@gmail.com>:
