### ISSUE TITLE
IP Request

### ISSUE THREAD

**Issue by Hsbas** [Yive/MCAPI-Support#11]
Hi!
Can you give me MCAPI receiver (whatever it is) IP adress? Because i'm using firewall in my server and my firewall rule is "Allow Just My Country". So i don't use mcapi because of that. I should add mcapi ip address in my firewall rule.

**Comment by Yive** [comment]
Unfortunately the IP of MCAPI is not publicly given out currently. Possibly will in the future once I figure out how to run a secondary php-fpm on a different IP from the main IP along side being on a separate domain.
