### ISSUE TITLE
I can't get file_get_contents

### ISSUE THREAD

**Issue by richicru** [Yive/MCAPI-Support#4]
I'm getting the warning:
"Warning: file_get_contents(http://mcapi.ca/query/es.minebone.com/info): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Temporarily Unavailable"
From my OVH host this is the result but from my other one.com hosting it works perfectly.
When I open the url in my browser it works too.

I guess that the api blocks in some way my ovh hosting. 
Any ideas? Thanks

**Comment by Yive** [comment]
I'm not 100% sure why that would happen with OVH. Sadly I'll need to get more reports about the site not working with OVH to see if it really is blocked, but I can ping my site and it's backend IP from one of my OVH boxes.

**Comment by Yive** [comment]
Assuming this issue hasn't happened again.
