### ISSUE TITLE
[ISSUE] Get Name by UUID

### ISSUE THREAD

**Issue by d3lp** [Yive/MCAPI-Support#7]
## API ##
[Name & UUID API](https://mcapi.ca/pages/docs/name-uuid)
## Description ##
Querying https://mcapi.ca/name/uuid/da6ab8ee71ad46d29529cf95df6902b9 results to:
```json
{
    "name": "da6ab8ee71ad46d29529cf95df6902b9",
    "uuid": "da6ab8ee71ad46d29529cf95df6902b9",
    "uuid_formatted": "da6ab8ee71ad46d29529cf95df6902b9"
}
```

Instead should result to:
```json
{
    "name": "Yive",
    "uuid": "da6ab8ee71ad46d29529cf95df6902b9",
    "uuid_formatted": "da6ab8ee-71ad-46d2-9529-cf95df6902b"
}
```

**Comment by Yive** [comment]
Sadly due to Mojang's rate limits, there is honestly no way for me to fix this. All of my proxies are getting rate limited. If I tried to make it 100% rate limitless, I would need at least 50 proxies.

**Comment by d3lp** [comment]
Okay. What about caching the results on your servers? As far as I know every UUID can be requested once per minute. You could cache them for one or two minutes an do a new query from the Mojang Servers as soon as the entry is expired.

Or you could implement this query for getting the right results: https://api.mojang.com/user/profiles/da6ab8ee71ad46d29529cf95df6902b9/names
```
[{"name":"Yive"}]
```

**Comment by Yive** [comment]
Yeah I already have caching set to one minute already. Just fixed it. Seems like it was an issue on my proxy's end. For some reason nginx locked up.
