### ISSUE TITLE
Server offline but is online

### ISSUE THREAD

**Issue by Pe46dro** [Yive/MCAPI-Support#8]
I tried MCAPI and it seem don't work with:
Minecraft PE Server ( Tested ip : mc.mcita.net:19132 )
BungeeCord old version (?) ( Tested ip : mc.wildadventure.it )

**Comment by Yive** [comment]
MCPE: MCPE uses UDP instead of TCP. I will look into adding support for MCPE.
Not really sure what you mean by bungeecord old version.
