### ISSUE TITLE
data doesn't display

### ISSUE THREAD

**Issue by Rhozlid** [Yive/MCAPI-Support#9]
hello, i want to display the MOTD of my server, this is the code:

<?php

$ip = $_GET["ip"];
$port = $_GET["port"];
$data = file_get_contents("https://mcapi.ca/query/" . $ip . ":" . $port . "/info");
$onlinePlayers = file_get_contents("https://mcapi.ca/query/$ip:$port/list");
$info = json_decode($data);
$onPlayers = json_decode($onlinePlayers);

$motd = $info->motd;
$status = $info->status;
$players = $info->players->online;
$maxplayers = $info->players->max;

echo "<h1> $ip:$port </h1>";
echo $motd;

?>

... but, this only display the ip:port, i am new using PHP, can someone tell me what is the error? thanks

**Comment by Collin1971** [comment]
Your script works fine for me, using `us.mineplex.com` as the IP and `25565` as the port.

**Comment by Rhozlid** [comment]
i still can't get this work..
try: http://rhozlid.tk/mc/

**Comment by Yive** [comment]
There's nothing wrong with the script, I tested it myself.

![Tested](http://i.tcpr.ca/54TLN55)

**Comment by Rhozlid** [comment]
when i try to get data from other game API, using var_dump i got this
![osu](https://cloud.githubusercontent.com/assets/13917414/10201789/1f80ec3c-6784-11e5-83b3-3ca3e1070a33.png)

but when i do it with the mcAPI..
![mc_ping](https://cloud.githubusercontent.com/assets/13917414/10201806/382ed23a-6784-11e5-9c86-86a3aa99e296.png)

**Comment by Yive** [comment]
I checked the IP in the url & it works, but not sure why it wont work for you.

**Comment by Rhozlid** [comment]
the "include_url_allow" on my web host is disabled, i need it enabled to do it?

**Comment by Yive** [comment]
Possibly, have you checked your error log when trying our mcapi?

**Comment by Rhozlid** [comment]
i dont know how to... i am using a Free web hosting

**Comment by Yive** [comment]
Don't really know if it'll work with free hosting then.

**Comment by Rhozlid** [comment]
the script works in Xampp... i will find a host where i can use the script.
![just testing](https://cloud.githubusercontent.com/assets/13917414/10212839/51abcc16-67db-11e5-92b7-6829189589e1.png)

so.. <h4>thanks for your replies!</h4>.
